"""
XtractR CASE/UCO Export Module (Issue #20)

Exports forensic case data to the Cyber-investigation Analysis Standard Expression
(CASE/UCO) ontology format for interoperability with other forensic tools.

Reference: https://caseontology.org/
Output Format: JSON-LD
"""

import json
import os
import logging
from datetime import datetime

logger = logging.getLogger("xtractr.reporting.case_uco")

CASE_CONTEXT = [
    "https://ontology.caseontology.org/case/case",
    "https://ontology.unifiedcyberontology.org/uco/uco",
]


def generate_case_bundle(case_id, manifest, evidence_dir):
    """
    Generate a CASE/UCO JSON-LD bundle from XtractR manifest data.
    
    Args:
        case_id: The case identifier
        manifest: The XtractR manifest dict
        evidence_dir: Path to the evidence output directory
    
    Returns:
        Path to the generated CASE bundle JSON-LD file
    """
    bundle = {
        "@context": CASE_CONTEXT,
        "@type": "case-core:Bundle",
        "case-core:name": f"XtractR Case Bundle: {case_id}",
        "case-core:description": "Forensic extraction results generated by XtractR",
        "uco-core:object": [],
    }

    # 1. Investigation object
    investigation = {
        "@id": f"urn:xtractr:investigation:{case_id}",
        "@type": "case-investigation:Investigation",
        "case-core:name": case_id,
        "uco-core:createdBy": {
            "@type": "uco-identity:Organization",
            "uco-core:name": "XtractR Forensic Framework",
        },
        "case-investigation:focus": "Android Device Forensics",
    }
    bundle["uco-core:object"].append(investigation)

    # 2. Provenance record (tool info)
    tool = {
        "@id": "urn:xtractr:tool:xtractr",
        "@type": "uco-tool:Tool",
        "uco-core:name": "XtractR",
        "uco-tool:version": manifest.get("case_metadata", {}).get("tool_version", "unknown"),
        "uco-tool:creator": "XtractR Project",
    }
    bundle["uco-core:object"].append(tool)

    # 3. Observable objects for each artifact
    artifact_layer = manifest.get("artifact_layer", {})
    for artifact_name, details in artifact_layer.items():
        observable = {
            "@id": f"urn:xtractr:observable:{case_id}:{artifact_name.replace(' ', '_')}",
            "@type": "uco-observable:ObservableObject",
            "uco-core:name": artifact_name,
            "uco-core:hasFacet": [],
        }

        # Content facet
        content_facet = {
            "@type": "uco-observable:ContentDataFacet",
            "uco-observable:hash": [],
        }

        src_hash = details.get("source_hash_sha256")
        if src_hash:
            content_facet["uco-observable:hash"].append({
                "@type": "uco-types:Hash",
                "uco-types:hashMethod": "SHA-256",
                "uco-types:hashValue": src_hash,
            })

        out_hash = details.get("output_hash_sha256")
        if out_hash:
            content_facet["uco-observable:hash"].append({
                "@type": "uco-types:Hash",
                "uco-types:hashMethod": "SHA-256",
                "uco-types:hashValue": out_hash,
            })

        observable["uco-core:hasFacet"].append(content_facet)

        # Extraction action
        action = {
            "@id": f"urn:xtractr:action:{case_id}:{artifact_name.replace(' ', '_')}",
            "@type": "case-investigation:InvestigativeAction",
            "uco-core:name": f"Extract {artifact_name}",
            "uco-action:result": details.get("status", "UNKNOWN"),
            "uco-action:object": observable["@id"],
            "uco-action:instrument": tool["@id"],
        }

        if details.get("record_count"):
            action["uco-core:description"] = f"{details['record_count']} records extracted"

        bundle["uco-core:object"].append(observable)
        bundle["uco-core:object"].append(action)

    # 4. Integrity assertion (Merkle root)
    integrity = manifest.get("integrity", {})
    assertion = {
        "@id": f"urn:xtractr:assertion:{case_id}:integrity",
        "@type": "uco-core:Assertion",
        "uco-core:name": "Case Integrity Seal",
        "uco-core:description": f"Merkle root: {integrity.get('merkle_root', 'N/A')}",
    }
    bundle["uco-core:object"].append(assertion)

    # Write the bundle
    output_path = os.path.join(evidence_dir, f"{case_id}_case_bundle.jsonld")
    with open(output_path, "w") as f:
        json.dump(bundle, f, indent=2)

    logger.info("CASE/UCO bundle written to: %s", output_path)
    return output_path
